// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_w0bfgXgFOhsd2mXist20voQg2a0Pbm4',
    appId: '1:618417660400:web:376e2256a217759f47fd35',
    messagingSenderId: '618417660400',
    projectId: 'fbase-dmo',
    authDomain: 'fbase-dmo.firebaseapp.com',
    storageBucket: 'fbase-dmo.appspot.com',
    measurementId: 'G-MMK84RSQBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0HwZF4Rhpcy3szNRS4TlWVcXeVIvMe-w',
    appId: '1:618417660400:android:a3e96074281e67ac47fd35',
    messagingSenderId: '618417660400',
    projectId: 'fbase-dmo',
    storageBucket: 'fbase-dmo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdqhDszyxdf9NKIBGKP_XizaYz_1FRAig',
    appId: '1:618417660400:ios:b891a7252534b1a347fd35',
    messagingSenderId: '618417660400',
    projectId: 'fbase-dmo',
    storageBucket: 'fbase-dmo.appspot.com',
    androidClientId: '618417660400-tsi23ps9eoquiaqifukpniraptdjknaj.apps.googleusercontent.com',
    iosClientId: '618417660400-8lvq458nimcnjj92k072v47pclprn28g.apps.googleusercontent.com',
    iosBundleId: 'hu.astar.employeetracking.web.astartappWeb',
  );
}
